### ISSUE TITLE
Unit test does not work

### ISSUE THREAD

**Issue by edubois** [Maghoumi/JitGRU#1]
Hi, just FYI, I get that with pytorch v1.4.0a0:

```
python jit_gru.py 
[2, 3]
[2, 3]
[2, 3]
[2, 3]
[2, 3]
Traceback (most recent call last):
  File "models/gru/jit_gru.py", line 184, in <module>
    test_script_gru_layer(5, 2, 3, 7)
  File "models/gru/jit_gru.py", line 146, in test_script_gru_layer
    assert lstm_param.shape == custom_param.shape
AssertionError
```

And printing:
```
print(custom_param.shape)
print(lstm_param.shape)
```
shows:
torch.Size([21, 7])
torch.Size([21, 3])

**Comment by Maghoumi** [comment]
Thank you for your bug report @edubois! I just pushed a commit to fix it.

Can you please verify that the fix is working for you?

**Comment by edubois** [comment]
Works now! Thanks!
